
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/MAE/Documents/MayaPython/QtFiles/InterruptSaveWidget/PEG_Settings.ui'
#
# Created: Tue Sep 18 10:23:07 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(756, 497)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.directoriesTextBrowser = QtWidgets.QTextBrowser(Form)
        self.directoriesTextBrowser.setObjectName("directoriesTextBrowser")
        self.verticalLayout.addWidget(self.directoriesTextBrowser)
        self.directoriesLineEdit = QtWidgets.QLineEdit(Form)
        self.directoriesLineEdit.setObjectName("directoriesLineEdit")
        self.verticalLayout.addWidget(self.directoriesLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddButtonDirect = QtWidgets.QPushButton(Form)
        self.AddButtonDirect.setObjectName("AddButtonDirect")
        self.horizontalLayout.addWidget(self.AddButtonDirect)
        self.DelButtonDirect = QtWidgets.QPushButton(Form)
        self.DelButtonDirect.setObjectName("DelButtonDirect")
        self.horizontalLayout.addWidget(self.DelButtonDirect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.helpButton = QtWidgets.QPushButton(Form)
        self.helpButton.setObjectName("helpButton")
        self.verticalLayout.addWidget(self.helpButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.DescTextBrowser = QtWidgets.QTextBrowser(Form)
        self.DescTextBrowser.setObjectName("DescTextBrowser")
        self.verticalLayout_2.addWidget(self.DescTextBrowser)
        self.DescLineEdit = QtWidgets.QLineEdit(Form)
        self.DescLineEdit.setObjectName("DescLineEdit")
        self.verticalLayout_2.addWidget(self.DescLineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DescAddButton = QtWidgets.QPushButton(Form)
        self.DescAddButton.setObjectName("DescAddButton")
        self.horizontalLayout_2.addWidget(self.DescAddButton)
        self.DescDelButton = QtWidgets.QPushButton(Form)
        self.DescDelButton.setObjectName("DescDelButton")
        self.horizontalLayout_2.addWidget(self.DescDelButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.StatesTextBrowser = QtWidgets.QTextBrowser(Form)
        self.StatesTextBrowser.setObjectName("StatesTextBrowser")
        self.verticalLayout_3.addWidget(self.StatesTextBrowser)
        self.StatesLineEdit = QtWidgets.QLineEdit(Form)
        self.StatesLineEdit.setObjectName("StatesLineEdit")
        self.verticalLayout_3.addWidget(self.StatesLineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StatesAddButton = QtWidgets.QPushButton(Form)
        self.StatesAddButton.setObjectName("StatesAddButton")
        self.horizontalLayout_3.addWidget(self.StatesAddButton)
        self.StatesDelButton = QtWidgets.QPushButton(Form)
        self.StatesDelButton.setObjectName("StatesDelButton")
        self.horizontalLayout_3.addWidget(self.StatesDelButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "PEG Settings", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Here is where you can change the default settings that PEG offers. The naming convention that PEG looks for goes like this: Name_Description_StateOfPipeline_Versioning. On this panel you can change what are acceptable answers for the Description section of the name, and for the State of Pipeline portion of the name. ", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Please note: If you do not tell PEG where you want it to watch for file names, it will not watch at all. Please specify file locations!", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Adjust the list of places you\'d like PEG to watch your file names.", None, -1))
        self.AddButtonDirect.setText(QtWidgets.QApplication.translate("Form", "Add!", None, -1))
        self.DelButtonDirect.setText(QtWidgets.QApplication.translate("Form", "Delete!", None, -1))
        self.helpButton.setText(QtWidgets.QApplication.translate("Form", "Help?!", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Change what is allowed in the Description that PEG looks for.", None, -1))
        self.DescAddButton.setText(QtWidgets.QApplication.translate("Form", "Add!", None, -1))
        self.DescDelButton.setText(QtWidgets.QApplication.translate("Form", "Delete!", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Change what is allowed in the State of Pipeline that PEG looks for.", None, -1))
        self.StatesAddButton.setText(QtWidgets.QApplication.translate("Form", "Add!", None, -1))
        self.StatesDelButton.setText(QtWidgets.QApplication.translate("Form", "Delete!", None, -1))

